export const Data = [
	{
		id: 1,
		Case_number: 1416,
		Title: "Technical Writer",
		Product: "Retail: Computer Software & Peripheral Equipment",
		Sub_Status: "Brightbean",
		Status: "Construction Foreman",
		Technician: "Data Coordiator",
		Technician_Status: "Violet",
		Technician_Date_Time: "2/14/2022",
		Account_Name: "tz1RVYrpXjnsbfMB2uEy3NgxXNYuyWRJb6sP",
		Contact_Name: "Fremont",
		Mobile: "1512344141",
		Comments: "sem sed sagittis nam congue risus semper",
		Phone: "6263938064",
		Address: "PO Box 32159",
		Opened_Time: "3/30/2022",
		Package: false,
		Billable: true,
		Amount: 92154,
		Priority: "Yearly",
		Agent: "Nichole",
		Remarks: "orchestrate e-business eyeballs",
		Channel: "Daily",
	  },{
		id: 2,
		Case_number: 1769,
		Title: "Administrative Assistant I",
		Product: "Telecommunications Equipment",
		Sub_Status: "Linkbuzz",
		Status: "Surveyor",
		Technician: "Social Worker",
		Technician_Status: "Red",
		Technician_Date_Time: "3/20/2022",
		Account_Name: "tz1gjUy857Gh1J7KcgzuCVzLsYYw7bokNT4J",
		Contact_Name: "Alfie",
		Mobile: "9825819820",
		Comments: "sed nisl nunc rhoncus dui",
		Phone: "1959235664",
		Address: "Room 810",
		Opened_Time: "5/7/2022",
		Package: true,
		Billable: true,
		Amount: 87214,
		Priority: "Once",
		Agent: "Cleavland",
		Remarks: "deliver best-of-breed applications",
		Channel: "Daily",
	  },{
		id: 3,
		Case_number: 1749,
		Title: "Marketing Assistant",
		Product: "Property-Casualty Insurers",
		Sub_Status: "Meevee",
		Status: "Construction Expeditor",
		Technician: "Developer II",
		Technician_Status: "Red",
		Technician_Date_Time: "12/13/2022",
		Account_Name: "tz1gDUUuJ6bSNcjQP2ZBJErZuwrPLHf1JmGD",
		Contact_Name: "Anatola",
		Mobile: "4541381567",
		Comments:
		  "id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate",
		Phone: "9384718106",
		Address: "Room 1977",
		Opened_Time: "2/25/2022",
		Package: true,
		Billable: true,
		Amount: 73838,
		Priority: "Never",
		Agent: "Jeno",
		Remarks: "incubate killer convergence",
		Channel: "Once",
	  },{
		id: 4,
		Case_number: 1504,
		Title: "Internal Auditor",
		Product: "Major Banks",
		Sub_Status: "Realcube",
		Status: "Construction Expeditor",
		Technician: "Librarian",
		Technician_Status: "Puce",
		Technician_Date_Time: "2/25/2022",
		Account_Name: "tz1RXnJv3JzhAMhbPwUQ7TxRE7jD63pdRJTL",
		Contact_Name: "Verla",
		Mobile: "2989061894",
		Comments:
		  "vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros",
		Phone: "9988930062",
		Address: "Apt 247",
		Opened_Time: "7/11/2022",
		Package: true,
		Billable: true,
		Amount: 68076,
		Priority: "Weekly",
		Agent: "Adan",
		Remarks: "brand clicks-and-mortar applications",
		Channel: "Never",
	  },{
		id: 5,
		Case_number: 1325,
		Title: "Financial Analyst",
		Product: "Business Services",
		Sub_Status: "Thoughtbridge",
		Status: "Subcontractor",
		Technician: "Associate Professor",
		Technician_Status: "Violet",
		Technician_Date_Time: "12/1/2022",
		Account_Name: "tz1SUd8REcg9r6nn2phirFf4VGmiZDoBYAfm",
		Contact_Name: "Rana",
		Mobile: "4575119997",
		Comments:
		  "suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit",
		Phone: "1983771902",
		Address: "PO Box 80347",
		Opened_Time: "12/15/2022",
		Package: true,
		Billable: true,
		Amount: 13497,
		Priority: "Daily",
		Agent: "Em",
		Remarks: "morph extensible action-items",
		Channel: "Yearly",
	  },{
		id: 6,
		Case_number: 1834,
		Title: "Recruiting Manager",
		Product: "Precious Metals",
		Sub_Status: "Skynoodle",
		Status: "Construction Manager",
		Technician: "Structural Engineer",
		Technician_Status: "Pink",
		Technician_Date_Time: "4/7/2022",
		Account_Name: "tz1VFejKq6AF445iK4zyDFL6qBmaVQbJ6c4Y",
		Contact_Name: "Emelen",
		Mobile: "9439614315",
		Comments: "justo sit amet sapien dignissim vestibulum vestibulum ante",
		Phone: "3812419467",
		Address: "2nd Floor",
		Opened_Time: "9/1/2022",
		Package: true,
		Billable: false,
		Amount: 24293,
		Priority: "Never",
		Agent: "Harris",
		Remarks: "optimize 24/7 e-commerce",
		Channel: "Never",
	  },{
		id: 7,
		Case_number: 1043,
		Title: "Nurse",
		Product: "Major Banks",
		Sub_Status: "Thoughtblab",
		Status: "Estimator",
		Technician: "Engineer IV",
		Technician_Status: "Puce",
		Technician_Date_Time: "10/4/2022",
		Account_Name: "tz1LznB6PZZWcsBMJbChUyN2iEY8B7VSddZF",
		Contact_Name: "Rowney",
		Mobile: "6141145973",
		Comments:
		  "proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante",
		Phone: "9966252738",
		Address: "PO Box 16061",
		Opened_Time: "3/9/2022",
		Package: true,
		Billable: false,
		Amount: 31629,
		Priority: "Seldom",
		Agent: "Merill",
		Remarks: "morph wireless ROI",
		Channel: "Seldom",
	  },{
		id: 8,
		Case_number: 1403,
		Title: "Pharmacist",
		Product: "Construction/Ag Equipment/Trucks",
		Sub_Status: "Twitterwire",
		Status: "Estimator",
		Technician: "Community Outreach Specialist",
		Technician_Status: "Fuscia",
		Technician_Date_Time: "10/26/2022",
		Account_Name: "tz1cfRgG6ZznfPDrHr1hfHvfmBsLV1WvPh5V",
		Contact_Name: "Druci",
		Mobile: "2332965459",
		Comments: "ante ipsum primis in faucibus orci luctus et ultrices",
		Phone: "9912730631",
		Address: "Suite 31",
		Opened_Time: "1/5/2023",
		Package: true,
		Billable: false,
		Amount: 23114,
		Priority: "Seldom",
		Agent: "Morton",
		Remarks: "strategize one-to-one markets",
		Channel: "Monthly",
	  },
	  {
		id: 9,
		Case_number: 1131,
		Title: "Professor",
		Product: "Computer Software: Prepackaged Software",
		Sub_Status: "Flipbug",
		Status: "Supervisor",
		Technician: "Speech Pathologist",
		Technician_Status: "Teal",
		Technician_Date_Time: "5/16/2022",
		Account_Name: "tz1dpC7MwP1gtp3sq65pXEaAAwtfH9q4RBKJ",
		Contact_Name: "Sarajane",
		Mobile: "4866703466",
		Comments:
		  "vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue",
		Phone: "2345091150",
		Address: "Room 946",
		Opened_Time: "4/27/2022",
		Package: false,
		Billable: true,
		Amount: 47092,
		Priority: "Often",
		Agent: "Shaughn",
		Remarks: "revolutionize sticky mindshare",
		Channel: "Weekly",
	  },
	  {
		id: 10,
		Case_number: 1827,
		Title: "Community Outreach Specialist",
		Product: "Life Insurance",
		Sub_Status: "Wikivu",
		Status: "Subcontractor",
		Technician: "Pharmacist",
		Technician_Status: "Green",
		Technician_Date_Time: "10/13/2022",
		Account_Name: "tz1TS4uLWa92WU99LxMCJhRuVhyPZ2io8kfF",
		Contact_Name: "Orion",
		Mobile: "2444420896",
		Comments:
		  "magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum",
		Phone: "0090493958",
		Address: "Room 1165",
		Opened_Time: "7/19/2022",
		Package: true,
		Billable: true,
		Amount: 90991,
		Priority: "Daily",
		Agent: "Bruno",
		Remarks: "revolutionize value-added partnerships",
		Channel: "Once",
	  },
	  {
		id: 11,
		Case_number: 1823,
		Title: "Senior Cost Accountant",
		Product: "Oil & Gas Production",
		Sub_Status: "Feedfish",
		Status: "Engineer",
		Technician: "Software Consultant",
		Technician_Status: "Khaki",
		Technician_Date_Time: "10/9/2022",
		Account_Name: "tz1hay1Dc7MGFNHe6RhscCfxpmmSH4PVVx75",
		Contact_Name: "Lauraine",
		Mobile: "8176140104",
		Comments: "convallis nunc proin at turpis a",
		Phone: "0681946679",
		Address: "PO Box 82849",
		Opened_Time: "7/22/2022",
		Package: false,
		Billable: true,
		Amount: 66092,
		Priority: "Daily",
		Agent: "Mano",
		Remarks: "reinvent vertical synergies",
		Channel: "Often",
	  },
	  {
		id: 12,
		Case_number: 1239,
		Title: "Technical Writer",
		Product: "Business Services",
		Sub_Status: "Wikido",
		Status: "Supervisor",
		Technician: "Sales Associate",
		Technician_Status: "Mauv",
		Technician_Date_Time: "8/13/2022",
		Account_Name: "tz1R3qMGAC4XBWjoE3UyWR9yLZwweMjR7mx4",
		Contact_Name: "Cecile",
		Mobile: "2559248646",
		Comments:
		  "molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac",
		Phone: "2173044559",
		Address: "Room 857",
		Opened_Time: "1/21/2023",
		Package: false,
		Billable: false,
		Amount: 69266,
		Priority: "Yearly",
		Agent: "Frederich",
		Remarks: "envisioneer holistic channels",
		Channel: "Monthly",
	  },
	  {
		id: 13,
		Case_number: 1299,
		Title: "VP Sales",
		Product: "n/a",
		Sub_Status: "Tagfeed",
		Status: "Construction Expeditor",
		Technician: "Mechanical Systems Engineer",
		Technician_Status: "Goldenrod",
		Technician_Date_Time: "4/28/2022",
		Account_Name: "tz1TFaAfHbTFN3EjdDJGQ9ye71uw1dTRvett",
		Contact_Name: "Madonna",
		Mobile: "0297512439",
		Comments:
		  "in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum",
		Phone: "4285663880",
		Address: "Room 1999",
		Opened_Time: "8/31/2022",
		Package: false,
		Billable: true,
		Amount: 59108,
		Priority: "Weekly",
		Agent: "Benjie",
		Remarks: "incentivize cutting-edge eyeballs",
		Channel: "Often",
	  },
	  {
		id: 14,
		Case_number: 1079,
		Title: "Senior Financial Analyst",
		Product: "n/a",
		Sub_Status: "Camimbo",
		Status: "Subcontractor",
		Technician: "Accounting Assistant III",
		Technician_Status: "Red",
		Technician_Date_Time: "6/1/2022",
		Account_Name: "tz1YeXxAL5DG1oo2TN42ukdjTLDUy5VDRUcn",
		Contact_Name: "Willabella",
		Mobile: "7507134822",
		Comments:
		  "vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
		Phone: "5378758734",
		Address: "19th Floor",
		Opened_Time: "9/15/2022",
		Package: false,
		Billable: false,
		Amount: 93527,
		Priority: "Seldom",
		Agent: "Camey",
		Remarks: "architect cutting-edge models",
		Channel: "Weekly",
	  },
	  {
		id: 15,
		Case_number: 1014,
		Title: "Associate Professor",
		Product: "Major Banks",
		Sub_Status: "Jabberstorm",
		Status: "Project Manager",
		Technician: "Associate Professor",
		Technician_Status: "Crimson",
		Technician_Date_Time: "2/8/2023",
		Account_Name: "tz1djUHDp69oAA7Nthd65kpPJk9rjMwzi7rG",
		Contact_Name: "Jehanna",
		Mobile: "2459222866",
		Comments:
		  "nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur",
		Phone: "4642179135",
		Address: "Apt 847",
		Opened_Time: "9/26/2022",
		Package: false,
		Billable: false,
		Amount: 90634,
		Priority: "Once",
		Agent: "Cirilo",
		Remarks: "innovate synergistic e-tailers",
		Channel: "Weekly",
	  },
	  {
		id: 16,
		Case_number: 1849,
		Title: "Occupational Therapist",
		Product: "n/a",
		Sub_Status: "Yadel",
		Status: "Engineer",
		Technician: "Account Executive",
		Technician_Status: "Crimson",
		Technician_Date_Time: "10/5/2022",
		Account_Name: "tz1RCrXiYoi1dwzj87JKbj2p8pmjL8yk4mbD",
		Contact_Name: "Hendrik",
		Mobile: "4294849487",
		Comments: "tortor quis turpis sed ante vivamus",
		Phone: "3549900759",
		Address: "19th Floor",
		Opened_Time: "3/15/2022",
		Package: false,
		Billable: false,
		Amount: 17859,
		Priority: "Often",
		Agent: "Boone",
		Remarks: "empower one-to-one users",
		Channel: "Seldom",
	  },
	  {
		id: 17,
		Case_number: 1402,
		Title: "Occupational Therapist",
		Product: "n/a",
		Sub_Status: "Centimia",
		Status: "Electrician",
		Technician: "VP Product Management",
		Technician_Status: "Puce",
		Technician_Date_Time: "1/29/2023",
		Account_Name: "tz1cbyTZZp3FggBR4du5mKytDuSYnH9cPSor",
		Contact_Name: "Nev",
		Mobile: "3022481438",
		Comments: "fermentum justo nec condimentum neque sapien",
		Phone: "3548505031",
		Address: "PO Box 69180",
		Opened_Time: "10/28/2022",
		Package: false,
		Billable: false,
		Amount: 20567,
		Priority: "Once",
		Agent: "Jeth",
		Remarks: "envisioneer sticky platforms",
		Channel: "Never",
	  },
	  {
		id: 18,
		Case_number: 1700,
		Title: "Registered Nurse",
		Product: "n/a",
		Sub_Status: "Quamba",
		Status: "Surveyor",
		Technician: "Programmer Analyst I",
		Technician_Status: "Orange",
		Technician_Date_Time: "11/11/2022",
		Account_Name: "tz1YN7ke2wr6f6R3qXTyHB6PpaKvsASUsTtA",
		Contact_Name: "Rand",
		Mobile: "7168782568",
		Comments:
		  "orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt",
		Phone: "7010422117",
		Address: "Room 1604",
		Opened_Time: "3/18/2022",
		Package: false,
		Billable: true,
		Amount: 19876,
		Priority: "Once",
		Agent: "Richard",
		Remarks: "leverage killer initiatives",
		Channel: "Daily",
	  },
  ];
  